language: node_js

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  # Honestly I don't like this hack.
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

node_js:
  - node
  - '6'

cache:
  apt: true
  directories:
    - "node_modules"

before_script:
  - ls /usr/lib/jvm/
  - "java -version"

before_deploy:
  - npm run compile
  - sed -i -e "/\/lib\//D" .gitignore
  - git config --global user.email "test@example.com"
  - git config --global user.name "Mr. Travis CI"
  - git add .
  - git commit -m "Commit to make tarball"
  - git archive --format=tar.gz --prefix=package/ -o ${TRAVIS_TAG}-compiled.tar.gz HEAD

deploy:
  - provider: releases
    api_key:
      secure: >-
        NReNxZYQ0IO5O/1axCc81WjrPZtIbL0iXCxm3YqE9N5UaNbEGPqCoHjrcMRu2WfCrDclNx
        /OJ286lq0U/XoY5AkKV9D/ENh2I+vHSNesM1v/3+GsNDbypFjebpgnkFPgut0hQMea/mZe
        JO8Y7dgfDJqb8uT8gc6GsNPD+SXWUWw=
    file: "${TRAVIS_TAG}-compiled.tar.gz"
    skip_cleanup: true
    on:
      repo: hiroaki-yamamoto/node-validator-nu
      tags: true
  - provider: npm
    email: hiroaki@hysoftware.net
    skip_cleanup: true
    api_key:
      secure: >-
        nO9LdBsCzwF/lvTQJ6zyuZTlhk85iGN5zftoHoNvQVGXbPvR8Qb9yZNyzz+X2svPagoulo
        RJ952zu+XXnlG9J3SdcYa9283bGQLXVcKxmCrSzTnrPhRz+oCCebTGpEjZtz7FXu6+LHjx
        X5JhLF7OmovOUv309d33t+u6KYtodcI=
    on:
      tags: true
